version: "3.8"

services:
  dokuwiki:
    image: linuxserver/dokuwiki:2020-07-29-ls52
    container_name: dokuwiki
    environment:
      - TZ=Europe/London
    networks:
      defnet:
        ipv4_address: 10.100.0.104
    restart: always
    volumes:
      - dokuwiki:/config

    ports:
      - "4010:80"

volumes:
  dokuwiki:

networks:
  defnet:
    external: true
