version: "3.8"

services:
  gitea:
    image: gitea/gitea:1
    container_name: gitea
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mariadb:3306
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - APP_NAME="Gitea - Garlicbready Main"
      - RUN_MODE=prod
    networks:
      defnet-prod:
        ipv4_address: 10.101.0.102
    restart: always
    volumes:
      - gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "9103:3000"
      - "222:22"

volumes:
  gitea:

networks:
  defnet-prod:
    external: true
