version: "3.8"

services:
  mariadb:
    image: mariadb:10.5.5
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
    networks:
      defnet-prod:
        ipv4_address: 10.101.0.100
    restart: always
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  mariadb:

networks:
  defnet-prod:
    external: true
