version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:2
    container_name: webproxymgr
    environment:
      DISABLE_IPV6: 'true'
    networks:
      defnet-prod:
        ipv4_address: 10.101.0.101
    restart: always
    
    ports:
      # Public HTTP Port:
      - '80:80'
      # Public HTTPS Port:
      - '443:443'
      # Admin Web Port
      - '9001:81'
      # Api Web Port:
      - '9002:3000'
    
    volumes:
      # This isn't needed directly, but just associates the volume with the container
      # To prevent it from being labled as unused / deletable
      - type: volume
        source: live_webproxymgr
        target: /notrequired

      # Configuration file
      - type: bind
        source: /mnt/vol2/var/docker/volumes/live_webproxymgr/_data/config.json
        target: /app/config/production.json

      # letsencrypt configuration
      - type: bind
        source: /mnt/vol2/var/docker/volumes/live_webproxymgr/_data/letsencrypt
        target: /etc/letsencrypt

      # Data directory for temp data
      - type: bind
        source: /mnt/vol2/var/docker/volumes/live_webproxymgr/_data/data
        target: /data

volumes:
  live_webproxymgr:
    external: true

networks:
  defnet-prod:
    external: true

